### ISSUE TITLE
Plotting errors on regions

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/osemosys2iamc#25]
I keep getting the following error when trying to plot using the code pasted below.
```python
{'model': 'OSeMBE v1.0.0', 'scenario': 'DIAG-Base'} ['Austria']
Plotting Austria
<class 'pyam.core.IamDataFrame'>
Index:
 * model    : OSeMBE v1.0.0 (1)
 * scenario : DIAG-Base (1)
Timeseries data coordinates:
   region   : Austria (1)
   variable : Primary Energy|Biomass|Electricity, ... Primary Energy|Wind (7)
   unit     : EJ/yr (1)
   year     : 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, ... 2060 (46)
Meta indicators:
   exclude (bool) False (1)
Traceback (most recent call last):
  File "/Users/wusher/miniconda3/envs/iamc/bin/osemosys2iamc", line 8, in <module>
    sys.exit(entry_point())
  File "/Users/wusher/repository/osemosys2iamc/src/osemosys2iamc/resultify.py", line 405, in entry_point
    make_plots(all_data, model, scenario, regions)
  File "/Users/wusher/repository/osemosys2iamc/src/osemosys2iamc/resultify.py", line 200, in make_plots
    data.plot.bar(ax=ax, stacked=True, title='Primary energy mix %s' % region)
  File "/Users/wusher/miniconda3/envs/iamc/lib/python3.9/site-packages/pyam/plotting.py", line 128, in bar
    return bar(self._parent, **kwargs)
  File "/Users/wusher/miniconda3/envs/iamc/lib/python3.9/site-packages/pyam/plotting.py", line 611, in bar
    raise ValueError(msg.format(col, x, bars))
ValueError: Can not plot multiple regions in bar plot with x=year, bars=variable
```

Here's the code currently implemented:

```python
def make_plots(df: pyam.IamDataFrame, model: str, scenario: str, regions: List[str]):
    """Creates standard plots

    Arguments
    ---------
    model: str
    scenario: str
    """

    args = dict(model=model, scenario=scenario)

    fig, ax = plt.subplots()

    for region in regions:
        # Plot primary energy
        data = df.filter(**args, variable='Primary Energy|*', region=region) # type: pyam.IamDataFrame
        if data:
            print(data)
            locator = mdates.AutoDateLocator(minticks=10)
            #locator.intervald['YEARLY'] = [10]
            data.plot.bar(ax=ax, stacked=True, title='Primary energy mix %s' % region)
            plt.legend(bbox_to_anchor=(0.,-0.5), loc='upper left')
            plt.tight_layout()
            ax.xaxis.set_major_locator(locator)
            fig.savefig('primary_energy_%s.pdf' % region, bbox_inches='tight', transparent=True, pad_inches=0)
            plt.clf()
```

**Comment by danielhuppmann** [comment]
Not quite sure about the particular error (I cannot reproduce it with my usual test dataset), see below - can you try to run this on your machine and see if you get the same error?

```python
TEST_DF = pd.DataFrame(
    [
        ["model_a", "scen_a", "World", "Primary Energy", "EJ/yr", 1, 6.0],
        ["model_a", "scen_a", "World", "Primary Energy|Coal", "EJ/yr", 0.5, 3],
        ["model_a", "scen_a", "Austria", "Primary Energy", "EJ/yr", 2, 7],
    ],
    columns=['model', 'scenario', 'region', 'variable', 'unit'] + [2005, 2010],
)

df = pyam.IamDataFrame(TEST_DF)

fig, ax = plt.subplots()

for r in ["World", "Austria"]:
    df.filter(**dict(model="model_a"), region=r).plot.bar(ax=ax, stacked=True, title='Primary energy mix %s' % r)
```
